### ISSUE TITLE
FMA issue 

### ISSUE THREAD

**Issue by calewis** [evaleev/libint#21]
This is a two part issue, I will issue a pull request to fix the second part.  

The question is 
Using an Intel Haswell-E cpu, when I run configure I get a message at the top saying that no FMA instructions will be used.  It says "Will not generate FMA instructions"

But then when trying to compile there is a compiler error in vector_x86.h when libint tries to compile code wrapped by the __FMA__ header guard.  

Is configure wrong about what it is doing, or is this the expected behavior? 

The error is due to vector_x86.h missing the intrinsics header that contains the mm_fmadd_pd instruction.  I will issue a pull request soon which includes the proper header along with a few other changes.

**Comment by evaleev** [comment]
configure has an `--enable-fma-instr` flag that enables emission of FMA-compatible code (i.e. code that can -- but not necessarily will -- be converted to FMA). You did not specify this flag, hence the message by configure.

The second part is a true error. That code was never tested because I do not have access to Haswell or Bulldozer. Please fix.

**Comment by calewis** [comment]
I'll issue a pull request tonight.

**Comment by calewis** [comment]
Issue should be fixed now that the correct header has been added.
