### ISSUE TITLE
Problems with the coefficients of two-electron integrals in Fock matrix

### ISSUE THREAD

**Issue by FreemanTheMaverick** [evaleev/libint#214]
Lines 764 to 767 of libint-2.5.0/tests/hartree-fock/hartree-fock.cc show that the negative contributions of two-electron integrals to Fock matrix have a coefficient of -1/4, but Eq.(3.154) on Page 141 of Modern Quantum Chemistry by A. Szabo and N. S. Oslund suggests the coefficient of -1/2. Why are they different? Thanks for any help.

**Comment by JensWehner** [comment]
Maybe restricted vs unrestricted calculations. The exchange integrals only work with same spin systems, so for closed shell systems they acquire a factor of 1/2. Just a guess.

**Comment by evaleev** [comment]
@FreemanTheMaverick Eq. 3.154 in SO loops over all integrals (note that the sum over lambda and sigma is not restricted to lambda >= sigma). If you rewrite the expression in terms of unique integrals then you will obtain the -1/4. Of course, only unique integrals should be computed, otherwise your code will be x2 (or x4, or x8 :) slower.
