### ISSUE TITLE
Library has no soversion

### ISSUE THREAD

**Issue by susilehtola** [evaleev/libint#306]
The library generated by the new CMake build system does not have a soversion.

**Comment by susilehtola** [comment]
ping @loriab

**Comment by loriab** [comment]
EFV didn't seem enthusiastic in #231, so I didn't push it. I've recently read some packaging guidelines that were a lot laxer (said ok to use M.m.p version for soname), but unfortunately I can't find them now.

Oh, fwiw, the current master / latest v2.8.0 _isn't_ the new CMake build system -- it's all the runtime changes from that work, not the buildtime overhaul.

**Comment by evaleev** [comment]
I am open to soversion but honestly there need to be some pretty thorough
guidelines. Trying to figure out what can trigger abi change for c++ is
beyond mortals' ability. I don't know how to test for abi compatibility for
example. Libint's built library is low level c++ so it is a bit easier, but
this may change since most codes want to use c++. Also, the Fortran module
stuff abi etc is beyond my normal horizon.

**Comment by loriab** [comment]
[ABI Lab](https://abi-laboratory.pro/index.php?view=open-source) is the only tool I know of right off for automated guidance ([openblas example](https://abi-laboratory.pro/index.php?view=timeline&l=openblas)). It does [run 200 checks](https://github.com/lvc/abi-compliance-checker) for c++ compliance but the repo hasn't been updated in a couple years.  conda-forge doesn't use soversion for reasoning, so I haven't had a problem with its absence.

**Comment by evaleev** [comment]
closed via #231
